"""
add is_verified to users

Revision ID: 7377b2ea12d1
Revises: d686f0a0e85b
Create Date: 2025-10-14 17:40:14.283299
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7377b2ea12d1'
down_revision = 'd686f0a0e85b'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###