"""init schema

Revision ID: 37eefb9032c6
Revises: 
Create Date: 2025-10-11 16:03:13.503378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37eefb9032c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'MATCHED', 'TIMEOUT', 'CANCELLED', name='matchstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.Column('timeout_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_requests_created_at'), 'match_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_match_requests_difficulty'), 'match_requests', ['difficulty'], unique=False)
    op.create_index(op.f('ix_match_requests_status'), 'match_requests', ['status'], unique=False)
    op.create_index(op.f('ix_match_requests_topic'), 'match_requests', ['topic'], unique=False)
    op.create_index(op.f('ix_match_requests_user_id'), 'match_requests', ['user_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request1_id', sa.String(), nullable=False),
    sa.Column('request2_id', sa.String(), nullable=False),
    sa.Column('user1_id', sa.String(), nullable=False),
    sa.Column('user2_id', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('user1_confirmed', sa.Boolean(), nullable=True),
    sa.Column('user2_confirmed', sa.Boolean(), nullable=True),
    sa.Column('collaboration_session_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_index(op.f('ix_match_requests_user_id'), table_name='match_requests')
    op.drop_index(op.f('ix_match_requests_topic'), table_name='match_requests')
    op.drop_index(op.f('ix_match_requests_status'), table_name='match_requests')
    op.drop_index(op.f('ix_match_requests_difficulty'), table_name='match_requests')
    op.drop_index(op.f('ix_match_requests_created_at'), table_name='match_requests')
    op.drop_table('match_requests')
    # ### end Alembic commands ###